### ISSUE TITLE
use const properly, esp in function signatures

### ISSUE THREAD

**Issue by karpathy** [karpathy/llm.c#147]
I wasn't diligent enough with my use of `float*` vs `const float*`. The former is used for outputs, the latter for inputs, to all functions. We'd like to refactor the function declarations to follow this paradigm, to be more defensive.

**Comment by rosslwheeler** [comment]
This one?

int check_tensor(float *a, float *b, int n, const char* label) { this one generates a couple of warnings

test_gpt2.cu(139): warning #2464-D: conversion from a string literal to "char *" is deprecated
test_gpt2.cu(141): warning #2464-D: conversion from a string literal to "char *" is deprecated

There's also these but wasn't sure if there's some incoming changes to use these variables?

test_gpt2.cu(56): warning #177-D: variable "maxT" was declared but never referenced
test_gpt2.cu(57): warning #177-D: variable "L" was declared but never referenced
test_gpt2.cu(95): warning C4101: 'losses': unreferenced local variable
