### ISSUE TITLE
__stcs in layernorm_forward_kernel3 function in train_gpt2.cu

### ISSUE THREAD

**Issue by Lang0722** [karpathy/llm.c#178]
In layernorm_forward_kernel3(), **__stcs** is used to intrinsically store the floating-point numbers. But according to the documentation, this function is used to store the **half-precision** floating-point numbers. Should it cover original floating-point to half-point by **__float2half**, then **__stcs**?

Related documentation: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__MISC.html

**Comment by karpathy** [comment]
This could very well be a bug. We only intend to handle floats so far, nothing below fp32 was introduced by intention so far. Except TF32 in cuBLAS sgemm

**Comment by Lang0722** [comment]
I now realize my mistake; being new to CUDA, I was unfamiliar with the "__stcs" function. My searches via Google and ChatGPT led me to its references in the CUDA math API, meant this function is only for half-precision. Nevertheless, the actual implementation in the code is properly explained here: [CUDA C Programming Guide on Store Functions Using Cache Hints](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#store-functions-using-cache-hints).

**Comment by karpathy** [comment]
ok, great ty for linking. closing
