### ISSUE TITLE
[.gitignore] gitignore does not ignore all binary files

### ISSUE THREAD

**Issue by ankitaggarwal011** [karpathy/llm.c#202]
`gpt2_tokenizer.bin` and other generated binary files `train_gpt2`, `test_gpt2`, etc are not ignored in the working git directory. One way can be to output all generated binary files to `bin/` directory and add `bin/` to `.gitignore`, though adding binary files individually to `.gitignore` might be sufficient?

**Comment by rosslwheeler** [comment]
If you're looking for a list which includes MSVC build artifacts, you can find them here: https://github.com/karpathy/llm.c/pull/134/files

**Comment by dagelf** [comment]
Would be better to update the paths to `data/` which is already ignored: `sed -i s@gpt2_@data/gpt2_@g *`

**Comment by dagelf** [comment]
Lets see if *.bin is ok #226
