### ISSUE TITLE
Possible NULL Pointer Dereference

### ISSUE THREAD

**Issue by RootUp** [karpathy/llm.c#308]
### Summary 

Not sure but by looking at the code roughly, I see in the below code snippet if `calloc` fails due to insufficient memory or any other reasons, it will return NULL. If either allocation fails, the code attempt to dereference a NULL pointer. 

```C
// lazily allocate the memory for m_memory and v_memory
if (model->m_memory == NULL) {
        model->m_memory = (float*)calloc(model->num_parameters, sizeof(float));
        model->v_memory = (float*)calloc(model->num_parameters, sizeof(float));
```

**Fix:** The ideal way is `calloc` should check or successfully allocate the memory before using the pointers.

**Comment by rosslwheeler** [comment]
Yes, this was reported already here. https://github.com/karpathy/llm.c/issues/10

**Comment by RootUp** [comment]
Thanks, I missed that. Closing this.
