### ISSUE TITLE
void tokenizer_init failed

### ISSUE THREAD

**Issue by Bing1002** [karpathy/llm.c#312]
allocated 474 MiB for model parameters
train_gpt2fp32cu: train_gpt2_fp32.cu:1815: void tokenizer_init(Tokenizer*, const char*): Assertion `header[1] == 1' failed.
[1]    2229854 abort (core dumped)  ./train_gpt2fp32cu

**Comment by azret** [comment]
Try to rebuild your data files with the train_gpt3.py. The tokenizer headers have changed.

**Comment by Bing1002** [comment]
Thank you for your response.
