### ISSUE TITLE
MultiGPU training hangs

### ISSUE THREAD

**Issue by chinthysl** [karpathy/llm.c#369]
mpirun with multiple GPUs is hanging after `allocated 474 MiB for master copy of params`
Most probably due to the introduction of cudastreams. @karpathy @PeterZhizhin

**Comment by karpathy** [comment]
Bleh I can reproduce this 🤦‍♂️ . Would most likely be helpful to harden our CI to include multi-GPU training, as it falls outside of it. iirc @Ricardicus helped set it up, not sure if he has knowledge of.

**Comment by Ricardicus** [comment]
Hardening the CI would be great. But the CI here on github workflows only reaches as far as to do the CPU test only unfortunately..  I don't see a way to include real GPU tests automatically up here.. It is different if we had our own hardware we could connect to and run jobs on, but that would have to be a different solution.

**Comment by ademeure** [comment]
Hmm, I can't immediately think of a reason why CUDA streams would break this, NCCL is still on the default stream which should keep everything synchronised both ways: https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html

One way to roughly restore the previous behaviour would be to replace this:
```cuda
    cudaCheck(cudaStreamCreate(&main_stream));
    cudaEventCreateWithFlags(&main_event, cudaEventDisableTiming);
    cudaEventCreateWithFlags(&loss_event, cudaEventDisableTiming);
    for (int i = 0; i < num_parallel_streams; i++) {
        cudaCheck(cudaStreamCreate(&parallel_streams[i]));
        cudaEventCreateWithFlags(&parallel_events[i], cudaEventDisableTiming);
    }
```
with this:
```cuda
    main_stream = 0;
    cudaEventCreateWithFlags(&main_event, cudaEventDisableTiming);
    cudaEventCreateWithFlags(&loss_event, cudaEventDisableTiming);
    for (int i = 0; i < num_parallel_streams; i++) {
        parallel_streams[i] = 0;
        cudaEventCreateWithFlags(&parallel_events[i], cudaEventDisableTiming);
    }
```
I don't have a multi-GPU setup to give this a try right now though...

**Comment by rosslwheeler** [comment]
Hangs for me too - trying @ademeure changes above now.

**Comment by chinthysl** [comment]
@Ricardicus @ademeure still hangs. changing nccl stream to main_stream doesn’t help. Will further look into multi stream usage and memcopyasyncs.

**Comment by rosslwheeler** [comment]
@karpathy @Ricardicus - I am asking about getting an Nvidia GPU CI runner for us. Will let you know as soon as I have some more info.

**Comment by pjj** [comment]
I don't have the bandwidth to dig further anytime soon, but in case it helps anyone else, the exact point that breaks multiGPU training on an 8-GPU node in today's TOT, is the first call to malloc_and_point, via malloc_and_point_activations

```
void* malloc_and_point(floatX** targets[], const size_t* act_sizes, size_t n) {
    size_t num_activations = 0;
    for (size_t i = 0; i < n; i++) {
        num_activations += act_sizes[i];
    }
    void* acts_memory;
    cudaCheck(cudaMalloc((void**)&acts_memory, num_activations * sizeof(floatX)));
```
that comes from the initialization of the activations below:
```
    // allocate space for all the activations if needed (done here, lazily)
    if(model->acts_memory == NULL) {
        // record the current B,T as well
        model->batch_size = B;
        model->seq_len = T;
        // allocate the space
        fill_in_activation_sizes(model->act_sizes, B, T, model->config);
        size_t num_activations = 0;
        for (size_t i = 0; i < NUM_ACTIVATION_TENSORS; i++) {
            num_activations += model->act_sizes[i];
        }
        model->num_activations = num_activations;
        model->acts_memory = malloc_and_point_activations(&model->acts, model->act_sizes);
```

I haven't analyzed the exact breaking point very carefully, but by watching the node via nvtop, it appears as if one of the processes using a GPU spawns another 8 of them all trying to allocate memory on the same GPU.  Here is a snapshot of part of nvidia-smi at about 1 second before the crash:  

```+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    107774      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     7276MiB |
|    0   N/A  N/A    107775      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107776      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107777      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107778      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107779      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107780      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    0   N/A  N/A    107781      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3626MiB |
|    1   N/A  N/A    107775      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    2   N/A  N/A    107776      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    3   N/A  N/A    107777      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    4   N/A  N/A    107778      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    5   N/A  N/A    107779      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    6   N/A  N/A    107780      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     4220MiB |
|    7   N/A  N/A    107781      C   ...xxxxxxxx/git/llm.c/./train_gpt2cu_2     3980MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by chinthysl** [comment]
Found the bug. `common_start` always set the gpu to idx 0. Doesn't take in MultiGPU config.
Working on the fix. @pjj thanks for the analysis above.
