### ISSUE TITLE
LLM.c in google colab

### ISSUE THREAD

**Issue by Eliah7** [karpathy/llm.c#562]
For those poor in GPUs, Google Colab can be an easy alternative to run and experiment with llm.c. Below is a sample notebook that allowed me to train the fp32 code. Only make sure to select the GPU runtime.

[https://colab.research.google.com/drive/1pFCqlGkfJiIr1HLTgaMh4i5OtiY7P96P?usp=sharing](https://colab.research.google.com/drive/1pFCqlGkfJiIr1HLTgaMh4i5OtiY7P96P?usp=sharing)

**Comment by gordicaleksa** [comment]
Cool thanks!

**Comment by thangnh0608** [comment]
When trying to use Google Colab free (T4 GPU), I got this error:

`
[CUDA ERROR] at file train_gpt2_fp32.cu:701:
the provided PTX was compiled with an unsupported toolchain.
`
can you help me to figure out?
