### ISSUE TITLE
Running `quick start on CPU` on Macbook Pro M2

### ISSUE THREAD

**Issue by full-stack-ai** [karpathy/llm.c#563]
Hi,

I am following the codes for `quick start (CPU)` and when running the `make train_gpt2`, I get the following error:

```
make: __nvcc_device_query: Command not found
---------------------------------------------
→ cuDNN is manually disabled by default, run make with `USE_CUDNN=1` to try to enable
✗ OpenMP not found
✗ Multi-GPU on CUDA on Darwin is not supported, skipping OpenMPI + NCCL support
✗ nvcc not found, skipping GPU/CUDA builds
---------------------------------------------
cc -Ofast -Wno-unused-result -Wno-ignored-pragmas -Wno-unknown-attributes -march=native   train_gpt2.c -lm -o train_gpt2
```

Does this mean that I can't run `llm.c` on mac?

I see that @karpathy has his running results on `Macbook Pro M3 Max`.

**Comment by rosslwheeler** [comment]
It's saying that you don't have NVCC which is because you're on a Mac. This is okay - I see the cc line so is it building or are there other errors?

**Comment by full-stack-ai** [comment]
Nothing seems to happen
![Screenshot 2024-06-06 at 3 50 41 PM](https://github.com/karpathy/llm.c/assets/157561277/eeb7bfa6-c9c6-4723-a21a-eae45dda2100)

**Comment by rosslwheeler** [comment]
Are the executable files there in the directory? Also, which version of gcc are you using?

**Comment by full-stack-ai** [comment]
Here is the repo files in the same directory:

![Screenshot 2024-06-06 at 9 26 58 PM](https://github.com/karpathy/llm.c/assets/157561277/490ba7db-97dd-490d-9619-c6edc5305443)

And gcc version:
cc -Ofast -Wno-unused-result -Wno-ignored-pragmas -Wno-unknown-attributes -march=native   train_gpt2.c -lm -o train_gpt2

**Comment by rosslwheeler** [comment]
Everything is there. train_gpt2 is built. You are good to go. Feel free to close this issue. Thanks.

**Comment by full-stack-ai** [comment]
So why the instruction is mentioned to run `make train_gpt2`? If `python train_gpt2.py` trains the model, then the documentation should change.

**Comment by gordicaleksa** [comment]
Hey @full-stack-ai ! There are 2 implementations in llm.c:
1) PyTorch reference implementation which is inside `train_gpt2.py` -> we only use it as a sanity check that our C implementation is correct.
2) C/CUDA implementation -> that's what you probably care about, to run it after building using `make` just run `./train_gpt2` in case you care about the CPU implementation.

Let me know if you need any additional help, your feedback is welcome!

Otherwise feel free to close the issue.
