### ISSUE TITLE
OSError: Memory mapping file failed: Cannot allocate memory

### ISSUE THREAD

**Issue by antonkratz** [karpathy/llm.c#566]
When I run `python dev/data/fineweb.py --version 10B` , I get an error `OSError: Memory mapping file failed: Cannot allocate memory`. Full log attached.

--
[note.txt](https://github.com/user-attachments/files/15740997/note.txt)

I am running this in a HPC context (ABCi cluster in Japan). I think each node has 384 GiB RAM.

**Comment by antonkratz** [comment]
I could not get to the root of the matter, but when submitting as a grid engine job instead of running it directly on the node, it seems to work.
Closing this issue.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
