### ISSUE TITLE
Precompute the scaling factor in gelu_forward and gelu_backward

### ISSUE THREAD

**Issue by ryanmcdermott** [karpathy/llm.c#57]
Thank you so much for the amazing repo!

The scaling factor in [gelu_forward](https://github.com/karpathy/llm.c/blob/d8e2a36f1538dbb38b43874731574aa9d224ef2a/train_gpt2.c#L339C5-L339C34) and [gelu_backward](https://github.com/karpathy/llm.c/blob/d8e2a36f1538dbb38b43874731574aa9d224ef2a/train_gpt2.c#L348) is computed each time the functions are run: `float s = sqrtf(2.0f / M_PI);`

This can be precomputed ahead of time and stored as a constant.

**Comment by ayushanshul07** [comment]
Is this good enough?

**Comment by andylolu2** [comment]
Doesn't it get optimised away by the compiler anyway? (Haven't actually checked though) Plus pointwise operations are bandwidth-limited anyway, so adding a few more flops shouldn't make a difference.

**Comment by karpathy** [comment]
fixed

**Comment by ayushanshul07** [comment]
Doesn't #defining constant is just replacement and the actual calculation is still repeated?
https://github.com/karpathy/llm.c/commit/f26cf00a615e4f643a3660071e4ef86010045db7
