### ISSUE TITLE
sel4 + llm.c > path to putting these llms in any mission critical system

### ISSUE THREAD

**Issue by torrmal** [karpathy/llm.c#622]
Hi team,

I was thinking that perhaps there is a way to run llm.c on a super secure and thin environment like sel4, 
https://sel4.systems/. 

Happy to brainstorm it, but just curious about thoughts on this idea first

**Comment by Wellplatform** [comment]
Good idea. My idea is to let LLM handle transaction scheduling. The transactions here can be RPC calls supported by seL4 using IPC. However, I don't know much about how to train LLM and how to master the priority and execution order of transactions based on training data.
