### ISSUE TITLE
[Suggestion] Discussions tab for general help

### ISSUE THREAD

**Issue by AndreSlavescu** [karpathy/llm.c#83]
Just as a simple suggestion, I'm wondering if there can be a discussion tab to post problems with running the system as opposed to posting individual issues. This can keep it more organized, and it's easier to track common threads. A simple point of comparison would be the discussion structure on the grok repository. Thoughts?

**Comment by karpathy** [comment]
Good idea, I tried to turn it on. I haven't used this before, let me know if it looks wrong somehow.

**Comment by AndreSlavescu** [comment]
I think it looks perfect. Maybe worth making a small PSA to move all general help questions to discussions as people are still posting in issues?
